name: Simple Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Display Env Vars
        run: |
          echo "Environment Variables"
          env

  deploy:
    runs-on: ubuntu-latest
