name: Simple Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: prod
    steps:
      - name: Display Env Vars
        run: |
          echo "Environment Variables"
          env

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        uses: actions/checkout@v2
        run: |
          echo "Deploying to Production environment..."
      
