name: Simple Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Display Env Vars
        run: |
          echo "Environment Variables"
          env

  deploy-prod:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          echo "Deploying to Production environment..."
          echo ${{ github.ref_name  }}
          echo ${{ github.ref  }}
      
